[masters]
master ansible_host={{ master_public_ip }} ansible_user=ubuntu

[workers]
worker ansible_host={{ worker_public_ip }} ansible_user=ubuntu

[kubernetes:children]
masters
workers

[kubernetes:vars]
ansible_ssh_private_key_file=~/.ssh/devops-keypem-ansible
ansible_ssh_common_args='-o StrictHostKeyChecking=no'